spring:
  application:
    name: Spring Boot Mutual TLS

server:
  port: 8443
  http2:
    enabled: true
  ssl:
    enabled: true
    protocol: TLSv1.2
    enabled-protocols: TLSv1.2+TLSv1.3
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
    key-alias: "test-server"
    key-store: "classpath:test-server-keystore.p12"
    key-store-password: "Server-5ECr3T!"
    key-password: "Server-5ECr3T!"
    trust-store: "classpath:test-server-keystore.p12"
    trust-store-password: "Server-5ECr3T!"
    client-auth: need
http:
  server:
    port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure.include: health,metrics
  endpoint.health.show-details: always

logging:
  level:
    org.springframework: WARN
    org.apache: WARN